//! # Search Engine Indexer Pipeline
//!
//! ## Current Architecture: Offline Batch Indexing
//! Currently, this indexer operates as an **offline batch processing** pipeline:
//! 1. Reads the complete raw document store (`documents.bin`) generated by the crawler.
//! 2. Tokenizes and indexes the corpus in memory, tracking term frequencies and positions.
//! 3. Computes a global PageRank pass via power iteration over the link graph.
//! 4. Encodes postings using Variable Byte (VByte) delta compression.
//! 5. Flushes monolithic index artifacts (`index.bin` and `dictionary.fst`).
//!
//! ### Limitations of Offline Batch Processing:
//! - **Stop-the-World Updates:** Inserting, modifying, or deleting a document requires
//!   a full re-index of the entire corpus ($O(N)$ re-indexing overhead).
//! - **High Freshness Latency:** Documents are unavailable for retrieval until the
//!   batch pipeline finishes and the search server re-opens/re-mmaps the index.
//! - **In-Place Mutation Overhead:** Compressed, delta-encoded postings lists cannot
//!   be efficiently mutated in-place on disk without shifting byte offsets.
//!
//! ---
//!
//! ## Modern Engine Architecture (Lucene, Tantivy): Immutable Segments & Background Merges
//! Modern production search engines (e.g., Apache Lucene, Tantivy) solve incremental
//! updates by adopting an **LSM-tree (Log-Structured Merge-Tree)** inspired architecture:
//!
//! 1. **In-Memory Buffers (`MemTable` / `SegmentWriter`):**
//!    - Incoming documents are parsed and indexed into a volatile RAM buffer
//!      (`DocumentsWriterPerThread` in Lucene, `SegmentWriter` in Tantivy).
//!    - Writes can be appended to an append-only Write-Ahead Log (WAL) for durability.
//!
//! 2. **Immutable Segments (Flushes):**
//!    - When the RAM buffer reaches a size threshold (e.g., 256MB) or an explicit commit
//!      interval fires, the buffer is serialized to disk as an **immutable segment**.
//!    - Each segment is a self-contained mini-index with its own postings, lexicon (FST),
//!      and doc metadata.
//!    - Because segments are strictly immutable once written, search threads can query
//!      them concurrently via memory-mapping (`mmap`) without read-write locking contention.
//!
//! 3. **Tombstone-Based Updates and Deletions:**
//!    - Instead of rewriting postings in place, document updates are executed as
//!      `Delete(doc_id) + Insert(new_doc)`.
//!    - Deletions are recorded in a lightweight deletion bitset / tombstone mask
//!      (e.g., Roaring Bitmaps or Tantivy `.del` files).
//!    - Queries filter candidate postings against the tombstone bitmap during evaluation.
//!
//! 4. **Background Merges (Compaction):**
//!    - Incremental flushes produce numerous small segments, increasing file handle usage
//!      and query overhead across segments ($O(S)$ where $S$ is the segment count).
//!    - A background merge policy (e.g., Lucene's `TieredMergePolicy`, Tantivy's `LogMergePolicy`)
//!      asynchronously selects segments of similar sizes and merges them:
//!      - Performs a k-way merge of sorted postings streams and remaps document IDs.
//!      - Physically purges deleted documents (tombstones) to reclaim storage.
//!      - Compiles a consolidated FST dictionary.
//!    - The engine updates its commit point atomically; active queries continue referencing
//!      older segments until their iterators finish, after which obsolete segment files are unlinked.

pub mod ranking;
pub mod storage;
pub mod tokenizer;

use fst::MapBuilder;
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;
use std::time::Instant;

use ranking::{
    compute_pagerank, search_combined_mmap, PageRankConfig, DEFAULT_ALPHA, DEFAULT_EPSILON,
};
use storage::{
    convert_json_to_bin_if_needed, BinaryIndexWriter, DocMetadata, IndexStore, MmapDocStore,
    MmapIndex, Posting, TermDictionary,
};
use tokenizer::TokenizerPipeline;

fn resolve_path(env_var: &str, candidates: &[&str]) -> String {
    if let Ok(val) = std::env::var(env_var) {
        return val;
    }
    for candidate in candidates {
        if Path::new(candidate).exists() {
            return candidate.to_string();
        }
    }
    candidates[0].to_string()
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let docs_json_path = resolve_path(
        "DOCS_JSON_PATH",
        &[
            "../crawler/documents.json",
            "crawler/documents.json",
            "documents.json",
        ],
    );
    let docs_bin_path = resolve_path(
        "DOCS_PATH",
        &[
            "../crawler/documents.bin",
            "crawler/documents.bin",
            "documents.bin",
        ],
    );
    let output_bin_index_path = resolve_path("INDEX_PATH", &["index.bin", "indexer/index.bin"]);
    let output_json_index_path =
        resolve_path("INDEX_JSON_PATH", &["index.json", "indexer/index.json"]);
    let output_fst_path = resolve_path("FST_PATH", &["dictionary.fst", "indexer/dictionary.fst"]);

    // Auto-convert JSON docs to binary storage if needed
    if !Path::new(&docs_bin_path).exists() && Path::new(&docs_json_path).exists() {
        convert_json_to_bin_if_needed(&docs_json_path, &docs_bin_path)?;
    }

    let pipeline = TokenizerPipeline::new();

    println!("Opening document store from {}...", docs_bin_path);
    let start_time = Instant::now();
    let doc_store = MmapDocStore::open(&docs_bin_path)?;
    let total_docs = doc_store.doc_count();
    println!(
        "Memory-mapped {} documents in {:?}",
        total_docs,
        start_time.elapsed()
    );

    // Build inverted index and metadata from mmap document store
    println!("Indexing documents...");
    let index_start = Instant::now();
    let mut inverted_index: HashMap<String, Vec<Posting>> = HashMap::new();
    let mut doc_metadata: Vec<DocMetadata> = Vec::with_capacity(total_docs as usize);
    let mut doc_lengths: Vec<u32> = Vec::with_capacity(total_docs as usize);
    let mut total_terms: usize = 0;
    let mut url_to_id: HashMap<String, usize> = HashMap::with_capacity(total_docs as usize);
    let mut doc_links: Vec<Vec<String>> = Vec::with_capacity(total_docs as usize);

    for doc_id in 0..total_docs {
        let doc = doc_store
            .get_doc(doc_id)
            .ok_or_else(|| format!("Failed to read doc {doc_id}"))?;

        url_to_id.insert(doc.url.to_string(), doc_id as usize);
        doc_links.push(doc.links.iter().map(|s| s.to_string()).collect());

        let title_terms = pipeline.tokenize(doc.title);
        let content_terms = pipeline.tokenize(doc.content);

        let mut all_terms = Vec::with_capacity(title_terms.len() + content_terms.len());
        all_terms.extend(title_terms);
        all_terms.extend(content_terms);

        let doc_length = all_terms.len() as u32;
        total_terms += doc_length as usize;
        doc_lengths.push(doc_length);

        doc_metadata.push(DocMetadata {
            internal_id: doc_id,
            hex_id: doc.id.to_string(),
            url: doc.url.to_string(),
            title: doc.title.to_string(),
            length: doc_length,
            pagerank: 0.0,
        });

        let mut term_positions: HashMap<String, Vec<u32>> = HashMap::new();
        for (pos, term) in all_terms.into_iter().enumerate() {
            term_positions.entry(term).or_default().push(pos as u32);
        }

        for (term, positions) in term_positions {
            let tf = positions.len() as u32;
            inverted_index.entry(term).or_default().push(Posting {
                doc_id,
                term_frequency: tf,
                positions,
            });
        }
    }

    let avg_doc_length = if total_docs > 0 {
        total_terms as f64 / total_docs as f64
    } else {
        0.0
    };

    println!(
        "Indexed {} documents ({} terms) in {:?}",
        total_docs,
        total_terms,
        index_start.elapsed()
    );

    // Compute PageRank via Power Iteration
    println!("Computing PageRank via Power Iteration pass...");
    let pagerank_start = Instant::now();
    let pagerank_scores = compute_pagerank(
        total_docs as usize,
        &doc_links,
        &url_to_id,
        &PageRankConfig::default(),
    );
    for (doc_id, &score) in pagerank_scores.iter().enumerate() {
        if doc_id < doc_metadata.len() {
            doc_metadata[doc_id].pagerank = score;
        }
    }
    println!(
        "Computed PageRank for {} documents in {:?}",
        total_docs,
        pagerank_start.elapsed()
    );

    // Sort terms lexicographically for FST and binary index
    let mut sorted_terms: Vec<String> = inverted_index.keys().cloned().collect();
    sorted_terms.sort();
    sorted_terms.dedup();

    println!("\n--- Indexing Statistics ---");
    println!("Total Documents: {}", total_docs);
    println!("Unique Vocabulary Terms: {}", sorted_terms.len());
    println!("Average Document Length: {:.2} terms", avg_doc_length);

    // Save binary memory-mapped index with VByte-compressed postings
    let bin_save_start = Instant::now();
    BinaryIndexWriter::write_index(
        &output_bin_index_path,
        total_docs,
        avg_doc_length,
        &doc_lengths,
        &pagerank_scores,
        &doc_metadata,
        &sorted_terms,
        &inverted_index,
    )?;
    println!(
        "Saved binary mmap index to {} with VByte postings in {:?}",
        output_bin_index_path,
        bin_save_start.elapsed()
    );

    // Build and save Lexicon FST (Map mapping term -> term_id)
    let fst_start = Instant::now();
    let fst_file = File::create(&output_fst_path)?;
    let fst_writer = BufWriter::new(fst_file);
    let mut builder = MapBuilder::new(fst_writer)?;
    for (term_idx, term) in sorted_terms.iter().enumerate() {
        builder.insert(term.as_bytes(), term_idx as u64)?;
    }
    builder.finish()?;
    println!(
        "Compiled and saved {} terms to {} in {:?}",
        sorted_terms.len(),
        output_fst_path,
        fst_start.elapsed()
    );

    // Save legacy index.json for backward compatibility
    let json_save_start = Instant::now();
    let mut doc_meta_map: HashMap<u32, DocMetadata> = HashMap::with_capacity(doc_metadata.len());
    for meta in doc_metadata {
        doc_meta_map.insert(meta.internal_id, meta);
    }
    let index_store = IndexStore {
        total_docs,
        avg_doc_length,
        doc_meta: doc_meta_map,
        inverted_index,
    };
    let json_bytes = serde_json::to_vec_pretty(&index_store)?;
    let mut out_file = File::create(&output_json_index_path)?;
    out_file.write_all(&json_bytes)?;
    println!(
        "Saved backward-compatible {} in {:?}",
        output_json_index_path,
        json_save_start.elapsed()
    );

    // Test BM25 & PageRank Query Evaluation using memory-mapped binary index
    println!("\nVerifying retrieval against memory-mapped binary index (mmap)...");
    let mmap_index = MmapIndex::open(&output_bin_index_path)?;
    let dictionary = TermDictionary::open(&output_fst_path)?;

    let test_queries = ["search engine", "page rank algorithm", "open source"];
    for query in test_queries {
        println!("\n--- Test Query: \"{}\" ---", query);
        let results = search_combined_mmap(
            query,
            &mmap_index,
            &dictionary,
            &pipeline,
            DEFAULT_ALPHA,
            DEFAULT_EPSILON,
            5,
        );
        for (rank, (doc, score)) in results.iter().enumerate() {
            println!(
                "{}. [{:.4}] (PR: {:.6}) {} ({})",
                rank + 1,
                score,
                doc.pagerank,
                doc.title,
                doc.url
            );
        }
    }

    Ok(())
}
