//! # Search Engine Indexer Pipeline
//!
//! ## Current Architecture: Offline Batch Indexing
//! Currently, this indexer operates as an **offline batch processing** pipeline:
//! 1. Reads the complete raw document store (`documents.bin`) generated by the crawler.
//! 2. Tokenizes and indexes the corpus in memory, tracking term frequencies and positions.
//! 3. Computes a global PageRank pass via power iteration over the link graph.
//! 4. Encodes postings using Variable Byte (VByte) delta compression.
//! 5. Flushes monolithic index artifacts (`index.bin` and `dictionary.fst`).
//!
//! ### Limitations of Offline Batch Processing:
//! - **Stop-the-World Updates:** Inserting, modifying, or deleting a document requires
//!   a full re-index of the entire corpus ($O(N)$ re-indexing overhead).
//! - **High Freshness Latency:** Documents are unavailable for retrieval until the
//!   batch pipeline finishes and the search server re-opens/re-mmaps the index.
//! - **In-Place Mutation Overhead:** Compressed, delta-encoded postings lists cannot
//!   be efficiently mutated in-place on disk without shifting byte offsets.
//!
//! ---
//!
//! ## Modern Engine Architecture (Lucene, Tantivy): Immutable Segments & Background Merges
//! Modern production search engines (e.g., Apache Lucene, Tantivy) solve incremental
//! updates by adopting an **LSM-tree (Log-Structured Merge-Tree)** inspired architecture:
//!
//! 1. **In-Memory Buffers (`MemTable` / `SegmentWriter`):**
//!    - Incoming documents are parsed and indexed into a volatile RAM buffer
//!      (`DocumentsWriterPerThread` in Lucene, `SegmentWriter` in Tantivy).
//!    - Writes can be appended to an append-only Write-Ahead Log (WAL) for durability.
//!
//! 2. **Immutable Segments (Flushes):**
//!    - When the RAM buffer reaches a size threshold (e.g., 256MB) or an explicit commit
//!      interval fires, the buffer is serialized to disk as an **immutable segment**.
//!    - Each segment is a self-contained mini-index with its own postings, lexicon (FST),
//!      and doc metadata.
//!    - Because segments are strictly immutable once written, search threads can query
//!      them concurrently via memory-mapping (`mmap`) without read-write locking contention.
//!
//! 3. **Tombstone-Based Updates and Deletions:**
//!    - Instead of rewriting postings in place, document updates are executed as
//!      `Delete(doc_id) + Insert(new_doc)`.
//!    - Deletions are recorded in a lightweight deletion bitset / tombstone mask
//!      (e.g., Roaring Bitmaps or Tantivy `.del` files).
//!    - Queries filter candidate postings against the tombstone bitmap during evaluation.
//!
//! 4. **Background Merges (Compaction):**
//!    - Incremental flushes produce numerous small segments, increasing file handle usage
//!      and query overhead across segments ($O(S)$ where $S$ is the segment count).
//!    - A background merge policy (e.g., Lucene's `TieredMergePolicy`, Tantivy's `LogMergePolicy`)
//!      asynchronously selects segments of similar sizes and merges them:
//!      - Performs a k-way merge of sorted postings streams and remaps document IDs.
//!      - Physically purges deleted documents (tombstones) to reclaim storage.
//!      - Compiles a consolidated FST dictionary.
//!    - The engine updates its commit point atomically; active queries continue referencing
//!      older segments until their iterators finish, after which obsolete segment files are unlinked.

use fst::automaton::{Levenshtein, Str};
use fst::{Automaton, IntoStreamer, Map, MapBuilder, Streamer};
use regex::Regex;
use rust_stemmers::{Algorithm, Stemmer};
use serde::{Deserialize, Serialize};
use std::collections::{BinaryHeap, HashMap, HashSet};
use std::fs::File;
use std::io::{BufReader, BufWriter, Seek, SeekFrom, Write};
use std::path::Path;
use std::time::Instant;

// ============================================================================
// Data Models
// ============================================================================

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct RawDocument {
    pub id: String,
    pub url: String,
    pub title: String,
    pub content: String,
    pub links: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct Posting {
    pub doc_id: u32,
    pub term_frequency: u32,
    pub positions: Vec<u32>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DocMetadata {
    pub internal_id: u32,
    pub hex_id: String,
    pub url: String,
    pub title: String,
    pub length: u32,
    #[serde(default)]
    pub pagerank: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct IndexStore {
    pub total_docs: u32,
    pub avg_doc_length: f64,
    pub doc_meta: HashMap<u32, DocMetadata>,
    pub inverted_index: HashMap<String, Vec<Posting>>,
}

// ============================================================================
// VByte Compression
// ============================================================================

#[inline]
pub fn encode_vbyte(mut val: u32, buf: &mut Vec<u8>) {
    while val >= 0x80 {
        buf.push(((val & 0x7F) as u8) | 0x80);
        val >>= 7;
    }
    buf.push((val & 0x7F) as u8);
}

#[inline]
pub fn decode_vbyte(bytes: &[u8], offset: &mut usize) -> Option<u32> {
    let mut result = 0u32;
    let mut shift = 0;
    while *offset < bytes.len() {
        if shift > 28 {
            return None;
        }
        let byte = bytes[*offset];
        *offset += 1;
        result |= ((byte & 0x7F) as u32) << shift;
        if (byte & 0x80) == 0 {
            return Some(result);
        }
        shift += 7;
    }
    None
}

pub fn encode_postings(postings: &[Posting], buf: &mut Vec<u8>) {
    let mut last_doc_id = 0u32;
    for (i, p) in postings.iter().enumerate() {
        let delta = if i == 0 {
            p.doc_id
        } else {
            p.doc_id.saturating_sub(last_doc_id)
        };
        last_doc_id = p.doc_id;
        encode_vbyte(delta, buf);
        let tf = if !p.positions.is_empty() {
            p.positions.len() as u32
        } else {
            p.term_frequency
        };
        encode_vbyte(tf, buf);
        let mut last_pos = 0u32;
        for (j, &pos) in p.positions.iter().enumerate() {
            let pos_delta = if j == 0 {
                pos
            } else {
                pos.saturating_sub(last_pos)
            };
            last_pos = pos;
            encode_vbyte(pos_delta, buf);
        }
    }
}

pub struct PostingsIterator<'a> {
    slice: &'a [u8],
    offset: usize,
    last_doc_id: u32,
    remaining: usize,
    index: usize,
}

impl<'a> PostingsIterator<'a> {
    pub fn new(slice: &'a [u8], doc_freq: usize) -> Self {
        Self {
            slice,
            offset: 0,
            last_doc_id: 0,
            remaining: doc_freq,
            index: 0,
        }
    }
}

impl<'a> Iterator for PostingsIterator<'a> {
    type Item = Posting;

    fn next(&mut self) -> Option<Self::Item> {
        if self.remaining == 0 {
            return None;
        }
        let delta = decode_vbyte(self.slice, &mut self.offset)?;
        let doc_id = if self.index == 0 {
            delta
        } else {
            self.last_doc_id + delta
        };
        self.last_doc_id = doc_id;
        self.index += 1;
        self.remaining -= 1;
        let term_frequency = decode_vbyte(self.slice, &mut self.offset).unwrap_or(0);
        let mut positions = Vec::with_capacity(term_frequency as usize);
        let mut last_pos = 0u32;
        for j in 0..term_frequency {
            let pos_delta = decode_vbyte(self.slice, &mut self.offset)?;
            let pos = if j == 0 {
                pos_delta
            } else {
                last_pos + pos_delta
            };
            last_pos = pos;
            positions.push(pos);
        }
        Some(Posting {
            doc_id,
            term_frequency,
            positions,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ScoredDoc {
    pub doc_id: u32,
    pub score: f64,
}

impl Eq for ScoredDoc {}

impl PartialOrd for ScoredDoc {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for ScoredDoc {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        // Min-heap ordering: reverse score so that smallest score has highest priority (popped first)
        other
            .score
            .partial_cmp(&self.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| self.doc_id.cmp(&other.doc_id))
    }
}

pub struct WandPostingCursor<'a> {
    slice: &'a [u8],
    offset: usize,
    last_doc_id: u32,
    remaining: usize,
    index: usize,
    pub current_doc_id: u32,
    pub current_tf: u32,
    pub idf: f64,
    pub max_score: f64,
    pub has_more: bool,
}

impl<'a> WandPostingCursor<'a> {
    pub fn new(slice: &'a [u8], doc_freq: usize, idf: f64, max_score: f64) -> Self {
        let mut cursor = Self {
            slice,
            offset: 0,
            last_doc_id: 0,
            remaining: doc_freq,
            index: 0,
            current_doc_id: 0,
            current_tf: 0,
            idf,
            max_score,
            has_more: false,
        };
        cursor.read_next();
        cursor
    }

    #[inline]
    pub fn read_next(&mut self) -> bool {
        if self.remaining == 0 {
            self.has_more = false;
            return false;
        }
        let Some(delta) = decode_vbyte(self.slice, &mut self.offset) else {
            self.has_more = false;
            return false;
        };
        let doc_id = if self.index == 0 {
            delta
        } else {
            self.last_doc_id + delta
        };
        self.last_doc_id = doc_id;
        self.index += 1;
        self.remaining -= 1;
        self.current_doc_id = doc_id;

        let tf = decode_vbyte(self.slice, &mut self.offset).unwrap_or(0);
        self.current_tf = tf;

        // Skip position deltas for this posting: tf VByte numbers
        for _ in 0..tf {
            while self.offset < self.slice.len() {
                let byte = self.slice[self.offset];
                self.offset += 1;
                if (byte & 0x80) == 0 {
                    break;
                }
            }
        }

        self.has_more = true;
        true
    }

    #[inline]
    pub fn advance_to(&mut self, target_doc_id: u32) -> bool {
        while self.has_more && self.current_doc_id < target_doc_id {
            self.read_next();
        }
        self.has_more
    }
}

// ============================================================================
// Binary Document Storage (documents.bin)
// ============================================================================

pub struct DocRecordRef<'a> {
    pub id: &'a str,
    pub url: &'a str,
    pub title: &'a str,
    pub content: &'a str,
    pub links: Vec<&'a str>,
}

pub struct DocStoreWriter {
    file: BufWriter<File>,
    doc_count: u32,
    offsets: Vec<(u64, u32)>,
    current_offset: u64,
}

impl DocStoreWriter {
    pub fn create<P: AsRef<Path>>(path: P) -> std::io::Result<Self> {
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);
        let placeholder = [0u8; 64];
        writer.write_all(&placeholder)?;
        Ok(Self {
            file: writer,
            doc_count: 0,
            offsets: Vec::new(),
            current_offset: 64,
        })
    }

    pub fn append(
        &mut self,
        id: &str,
        url: &str,
        title: &str,
        content: &str,
        links: &[String],
    ) -> std::io::Result<u32> {
        let start_offset = self.current_offset;
        let mut written = 0u32;

        let id_bytes = id.as_bytes();
        self.file
            .write_all(&(id_bytes.len() as u16).to_le_bytes())?;
        self.file.write_all(id_bytes)?;
        written += 2 + id_bytes.len() as u32;

        let url_bytes = url.as_bytes();
        self.file
            .write_all(&(url_bytes.len() as u16).to_le_bytes())?;
        self.file.write_all(url_bytes)?;
        written += 2 + url_bytes.len() as u32;

        let title_bytes = title.as_bytes();
        self.file
            .write_all(&(title_bytes.len() as u16).to_le_bytes())?;
        self.file.write_all(title_bytes)?;
        written += 2 + title_bytes.len() as u32;

        let content_bytes = content.as_bytes();
        self.file
            .write_all(&(content_bytes.len() as u32).to_le_bytes())?;
        self.file.write_all(content_bytes)?;
        written += 4 + content_bytes.len() as u32;

        self.file.write_all(&(links.len() as u32).to_le_bytes())?;
        written += 4;
        for link in links {
            let link_bytes = link.as_bytes();
            self.file
                .write_all(&(link_bytes.len() as u16).to_le_bytes())?;
            self.file.write_all(link_bytes)?;
            written += 2 + link_bytes.len() as u32;
        }

        self.offsets.push((start_offset, written));
        self.current_offset += written as u64;
        let doc_id = self.doc_count;
        self.doc_count += 1;
        Ok(doc_id)
    }

    pub fn finish(mut self) -> std::io::Result<u32> {
        let index_offset = self.current_offset;
        for (offset, len) in &self.offsets {
            self.file.write_all(&offset.to_le_bytes())?;
            self.file.write_all(&len.to_le_bytes())?;
        }
        self.file.flush()?;

        let mut file = self.file.into_inner().map_err(|e| e.into_error())?;
        file.seek(SeekFrom::Start(0))?;
        file.write_all(b"MSEDOC01")?;
        file.write_all(&self.doc_count.to_le_bytes())?;
        file.write_all(&index_offset.to_le_bytes())?;
        let padding = [0u8; 44];
        file.write_all(&padding)?;
        file.flush()?;
        Ok(self.doc_count)
    }
}

pub struct MmapDocStore {
    mmap: memmap2::Mmap,
    doc_count: u32,
    index_offset: usize,
}

impl MmapDocStore {
    pub fn open<P: AsRef<Path>>(path: P) -> std::io::Result<Self> {
        let file = File::open(path)?;
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        if mmap.len() < 64 || &mmap[0..8] != b"MSEDOC01" {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Invalid document store magic header",
            ));
        }
        let doc_count = u32::from_le_bytes(mmap[8..12].try_into().unwrap());
        let index_offset = u64::from_le_bytes(mmap[12..20].try_into().unwrap()) as usize;
        Ok(Self {
            mmap,
            doc_count,
            index_offset,
        })
    }

    pub fn doc_count(&self) -> u32 {
        self.doc_count
    }

    pub fn get_doc_slice(&self, doc_id: u32) -> Option<&[u8]> {
        if doc_id >= self.doc_count {
            return None;
        }
        let entry_offset = self.index_offset + (doc_id as usize) * 12;
        if entry_offset + 12 > self.mmap.len() {
            return None;
        }
        let offset = u64::from_le_bytes(
            self.mmap[entry_offset..entry_offset + 8]
                .try_into()
                .unwrap(),
        ) as usize;
        let len = u32::from_le_bytes(
            self.mmap[entry_offset + 8..entry_offset + 12]
                .try_into()
                .unwrap(),
        ) as usize;
        if offset + len > self.mmap.len() {
            return None;
        }
        Some(&self.mmap[offset..offset + len])
    }

    pub fn get_doc(&self, doc_id: u32) -> Option<DocRecordRef<'_>> {
        let slice = self.get_doc_slice(doc_id)?;
        let mut pos = 0;
        if slice.len() < 2 {
            return None;
        }
        let id_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        if pos + id_len > slice.len() {
            return None;
        }
        let id = std::str::from_utf8(&slice[pos..pos + id_len]).ok()?;
        pos += id_len;

        if pos + 2 > slice.len() {
            return None;
        }
        let url_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        if pos + url_len > slice.len() {
            return None;
        }
        let url = std::str::from_utf8(&slice[pos..pos + url_len]).ok()?;
        pos += url_len;

        if pos + 2 > slice.len() {
            return None;
        }
        let title_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        if pos + title_len > slice.len() {
            return None;
        }
        let title = std::str::from_utf8(&slice[pos..pos + title_len]).ok()?;
        pos += title_len;

        if pos + 4 > slice.len() {
            return None;
        }
        let content_len =
            u32::from_le_bytes([slice[pos], slice[pos + 1], slice[pos + 2], slice[pos + 3]])
                as usize;
        pos += 4;
        if pos + content_len > slice.len() {
            return None;
        }
        let content = std::str::from_utf8(&slice[pos..pos + content_len]).ok()?;
        pos += content_len;

        let mut links = Vec::new();
        if pos + 4 <= slice.len() {
            let links_count =
                u32::from_le_bytes([slice[pos], slice[pos + 1], slice[pos + 2], slice[pos + 3]])
                    as usize;
            pos += 4;
            links.reserve(links_count);
            for _ in 0..links_count {
                if pos + 2 > slice.len() {
                    break;
                }
                let link_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
                pos += 2;
                if pos + link_len > slice.len() {
                    break;
                }
                if let Ok(link_str) = std::str::from_utf8(&slice[pos..pos + link_len]) {
                    links.push(link_str);
                }
                pos += link_len;
            }
        }

        Some(DocRecordRef {
            id,
            url,
            title,
            content,
            links,
        })
    }
}

// Convert JSON documents to binary document store if needed
pub fn convert_json_to_bin_if_needed(json_path: &str, bin_path: &str) -> std::io::Result<()> {
    if Path::new(bin_path).exists() {
        return Ok(());
    }
    if !Path::new(json_path).exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("Neither {bin_path} nor {json_path} found"),
        ));
    }
    println!("Converting {json_path} to {bin_path} (binary document storage)...");
    let start = Instant::now();
    let file = File::open(json_path)?;
    let reader = BufReader::new(file);
    let docs: Vec<RawDocument> = serde_json::from_reader(reader)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

    let mut writer = DocStoreWriter::create(bin_path)?;
    for doc in &docs {
        writer.append(&doc.id, &doc.url, &doc.title, &doc.content, &doc.links)?;
    }
    let count = writer.finish()?;
    println!(
        "Converted {count} documents to {bin_path} in {:?}",
        start.elapsed()
    );
    Ok(())
}

// ============================================================================
// Binary Inverted Index (index.bin)
// ============================================================================

pub struct TermEntry {
    pub postings_offset: u64,
    pub postings_len: u32,
    pub doc_freq: u32,
}

pub struct DocMetaRef<'a> {
    pub hex_id: &'a str,
    pub url: &'a str,
    pub title: &'a str,
    pub pagerank: f64,
}

pub struct BinaryIndexWriter;

impl BinaryIndexWriter {
    #[allow(clippy::too_many_arguments)]
    pub fn write_index<P: AsRef<Path>>(
        path: P,
        total_docs: u32,
        avg_doc_length: f64,
        doc_lengths: &[u32],
        pagerank: &[f64],
        doc_metadata: &[DocMetadata],
        sorted_terms: &[String],
        inverted_index: &HashMap<String, Vec<Posting>>,
    ) -> std::io::Result<()> {
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);

        // Header placeholder (128 bytes)
        let placeholder = [0u8; 128];
        writer.write_all(&placeholder)?;
        let mut current_offset = 128u64;

        // 1. Doc Lengths
        let doc_lengths_offset = current_offset;
        for &len in doc_lengths {
            writer.write_all(&len.to_le_bytes())?;
        }
        current_offset += (doc_lengths.len() * 4) as u64;

        // 2. PageRank
        let pagerank_offset = current_offset;
        for &pr in pagerank {
            writer.write_all(&pr.to_le_bytes())?;
        }
        current_offset += (pagerank.len() * 8) as u64;

        // 3. Doc Meta Index & Data
        let doc_meta_index_offset = current_offset;
        let mut meta_offsets = Vec::with_capacity(doc_metadata.len() + 1);
        let mut meta_data_bytes = Vec::new();

        for meta in doc_metadata {
            let offset_rel = meta_data_bytes.len() as u64;
            meta_offsets.push(offset_rel);

            let hex_bytes = meta.hex_id.as_bytes();
            meta_data_bytes.extend_from_slice(&(hex_bytes.len() as u16).to_le_bytes());
            meta_data_bytes.extend_from_slice(hex_bytes);

            let url_bytes = meta.url.as_bytes();
            meta_data_bytes.extend_from_slice(&(url_bytes.len() as u16).to_le_bytes());
            meta_data_bytes.extend_from_slice(url_bytes);

            let title_bytes = meta.title.as_bytes();
            meta_data_bytes.extend_from_slice(&(title_bytes.len() as u16).to_le_bytes());
            meta_data_bytes.extend_from_slice(title_bytes);
        }
        meta_offsets.push(meta_data_bytes.len() as u64);

        for &off in &meta_offsets {
            writer.write_all(&off.to_le_bytes())?;
        }
        current_offset += (meta_offsets.len() * 8) as u64;

        let doc_meta_data_offset = current_offset;
        writer.write_all(&meta_data_bytes)?;
        current_offset += meta_data_bytes.len() as u64;

        // 3. Postings block (VByte-compressed)
        // First encode all postings so we know offsets and lengths
        let mut postings_bytes = Vec::new();
        let mut term_entries = Vec::with_capacity(sorted_terms.len());

        for term in sorted_terms {
            let postings = inverted_index
                .get(term)
                .map(|v| v.as_slice())
                .unwrap_or(&[]);
            let p_offset = postings_bytes.len() as u64;
            let mut buf = Vec::new();
            encode_postings(postings, &mut buf);
            let p_len = buf.len() as u32;
            postings_bytes.extend_from_slice(&buf);
            term_entries.push(TermEntry {
                postings_offset: p_offset,
                postings_len: p_len,
                doc_freq: postings.len() as u32,
            });
        }

        // 4. Terms Table
        let terms_table_offset = current_offset;
        for entry in &term_entries {
            writer.write_all(&entry.postings_offset.to_le_bytes())?;
            writer.write_all(&entry.postings_len.to_le_bytes())?;
            writer.write_all(&entry.doc_freq.to_le_bytes())?;
        }
        current_offset += (term_entries.len() * 16) as u64;

        // 5. Terms Strings Table
        let terms_strings_offset = current_offset;
        let mut term_offsets = Vec::with_capacity(sorted_terms.len() + 1);
        let mut term_data = Vec::new();
        for term in sorted_terms {
            term_offsets.push(term_data.len() as u32);
            term_data.extend_from_slice(term.as_bytes());
        }
        term_offsets.push(term_data.len() as u32);

        for &off in &term_offsets {
            writer.write_all(&off.to_le_bytes())?;
        }
        current_offset += (term_offsets.len() * 4) as u64;

        writer.write_all(&term_data)?;
        current_offset += term_data.len() as u64;

        // 6. Postings Block
        let postings_offset = current_offset;
        writer.write_all(&postings_bytes)?;
        let postings_bytes_len = postings_bytes.len() as u64;

        writer.flush()?;

        // Seek back to 0 and write final header
        let mut file = writer.into_inner().map_err(|e| e.into_error())?;
        file.seek(SeekFrom::Start(0))?;
        file.write_all(b"MSEIDX01")?;
        file.write_all(&total_docs.to_le_bytes())?;
        file.write_all(&avg_doc_length.to_le_bytes())?;
        file.write_all(&doc_lengths_offset.to_le_bytes())?;
        file.write_all(&doc_meta_index_offset.to_le_bytes())?;
        file.write_all(&doc_meta_data_offset.to_le_bytes())?;
        file.write_all(&terms_table_offset.to_le_bytes())?;
        file.write_all(&(sorted_terms.len() as u32).to_le_bytes())?;
        file.write_all(&terms_strings_offset.to_le_bytes())?;
        file.write_all(&postings_offset.to_le_bytes())?;
        file.write_all(&postings_bytes_len.to_le_bytes())?;
        file.write_all(&pagerank_offset.to_le_bytes())?;
        let padding = [0u8; 40];
        file.write_all(&padding)?;
        file.flush()?;

        Ok(())
    }
}

pub struct MmapIndex {
    mmap: memmap2::Mmap,
    pub total_docs: u32,
    pub avg_doc_length: f64,
    pub num_terms: u32,
    doc_lengths_offset: usize,
    pagerank_offset: usize,
    doc_meta_index_offset: usize,
    doc_meta_data_offset: usize,
    terms_table_offset: usize,
    terms_strings_offset: usize,
    postings_offset: usize,
}

impl MmapIndex {
    pub fn open<P: AsRef<Path>>(path: P) -> std::io::Result<Self> {
        let file = File::open(path)?;
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        if mmap.len() < 128 || &mmap[0..8] != b"MSEIDX01" {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Invalid index magic header",
            ));
        }
        let total_docs = u32::from_le_bytes(mmap[8..12].try_into().unwrap());
        let avg_doc_length = f64::from_le_bytes(mmap[12..20].try_into().unwrap());
        let doc_lengths_offset = u64::from_le_bytes(mmap[20..28].try_into().unwrap()) as usize;
        let doc_meta_index_offset = u64::from_le_bytes(mmap[28..36].try_into().unwrap()) as usize;
        let doc_meta_data_offset = u64::from_le_bytes(mmap[36..44].try_into().unwrap()) as usize;
        let terms_table_offset = u64::from_le_bytes(mmap[44..52].try_into().unwrap()) as usize;
        let num_terms = u32::from_le_bytes(mmap[52..56].try_into().unwrap());
        let terms_strings_offset = u64::from_le_bytes(mmap[56..64].try_into().unwrap()) as usize;
        let postings_offset = u64::from_le_bytes(mmap[64..72].try_into().unwrap()) as usize;
        let pagerank_offset = if mmap.len() >= 88 {
            u64::from_le_bytes(mmap[80..88].try_into().unwrap()) as usize
        } else {
            0
        };

        Ok(Self {
            mmap,
            total_docs,
            avg_doc_length,
            num_terms,
            doc_lengths_offset,
            pagerank_offset,
            doc_meta_index_offset,
            doc_meta_data_offset,
            terms_table_offset,
            terms_strings_offset,
            postings_offset,
        })
    }

    #[inline]
    pub fn get_doc_length(&self, doc_id: u32) -> u32 {
        if doc_id >= self.total_docs {
            return 0;
        }
        let off = self.doc_lengths_offset + (doc_id as usize) * 4;
        u32::from_le_bytes(self.mmap[off..off + 4].try_into().unwrap())
    }

    #[inline]
    pub fn get_pagerank(&self, doc_id: u32) -> f64 {
        if doc_id >= self.total_docs || self.pagerank_offset == 0 {
            return if self.total_docs > 0 {
                1.0 / (self.total_docs as f64)
            } else {
                0.0
            };
        }
        let off = self.pagerank_offset + (doc_id as usize) * 8;
        if off + 8 > self.mmap.len() {
            return if self.total_docs > 0 {
                1.0 / (self.total_docs as f64)
            } else {
                0.0
            };
        }
        f64::from_le_bytes(self.mmap[off..off + 8].try_into().unwrap())
    }

    pub fn get_doc_meta(&self, doc_id: u32) -> Option<DocMetaRef<'_>> {
        if doc_id >= self.total_docs {
            return None;
        }
        let idx_off = self.doc_meta_index_offset + (doc_id as usize) * 8;
        let meta_rel_start =
            u64::from_le_bytes(self.mmap[idx_off..idx_off + 8].try_into().unwrap()) as usize;
        let meta_rel_end =
            u64::from_le_bytes(self.mmap[idx_off + 8..idx_off + 16].try_into().unwrap()) as usize;

        let start = self.doc_meta_data_offset + meta_rel_start;
        let end = self.doc_meta_data_offset + meta_rel_end;
        if end > self.mmap.len() || start >= end {
            return None;
        }
        let slice = &self.mmap[start..end];
        let mut pos = 0;
        if slice.len() < 2 {
            return None;
        }
        let hex_id_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        let hex_id = std::str::from_utf8(&slice[pos..pos + hex_id_len]).ok()?;
        pos += hex_id_len;

        if pos + 2 > slice.len() {
            return None;
        }
        let url_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        let url = std::str::from_utf8(&slice[pos..pos + url_len]).ok()?;
        pos += url_len;

        if pos + 2 > slice.len() {
            return None;
        }
        let title_len = u16::from_le_bytes([slice[pos], slice[pos + 1]]) as usize;
        pos += 2;
        let title = std::str::from_utf8(&slice[pos..pos + title_len]).ok()?;

        let pagerank = self.get_pagerank(doc_id);

        Some(DocMetaRef {
            hex_id,
            url,
            title,
            pagerank,
        })
    }

    #[inline]
    pub fn get_term_entry(&self, term_idx: usize) -> Option<TermEntry> {
        if term_idx >= self.num_terms as usize {
            return None;
        }
        let off = self.terms_table_offset + term_idx * 16;
        if off + 16 > self.mmap.len() {
            return None;
        }
        let postings_offset = u64::from_le_bytes(self.mmap[off..off + 8].try_into().unwrap());
        let postings_len = u32::from_le_bytes(self.mmap[off + 8..off + 12].try_into().unwrap());
        let doc_freq = u32::from_le_bytes(self.mmap[off + 12..off + 16].try_into().unwrap());
        Some(TermEntry {
            postings_offset,
            postings_len,
            doc_freq,
        })
    }

    #[inline]
    pub fn get_postings_slice(&self, entry: &TermEntry) -> &[u8] {
        let start = self.postings_offset + entry.postings_offset as usize;
        let end = start + entry.postings_len as usize;
        &self.mmap[start..end]
    }

    pub fn get_term_str(&self, term_idx: usize) -> Option<&str> {
        if term_idx >= self.num_terms as usize {
            return None;
        }
        let off = self.terms_strings_offset + term_idx * 4;
        let s_start = u32::from_le_bytes(self.mmap[off..off + 4].try_into().unwrap()) as usize;
        let s_end = u32::from_le_bytes(self.mmap[off + 4..off + 8].try_into().unwrap()) as usize;
        let data_base = self.terms_strings_offset + (self.num_terms as usize + 1) * 4;
        let start = data_base + s_start;
        let end = data_base + s_end;
        if end > self.mmap.len() {
            return None;
        }
        std::str::from_utf8(&self.mmap[start..end]).ok()
    }
}

// ============================================================================
// Term Dictionary FST (using fst::Map)
// ============================================================================

pub struct TermDictionary {
    fst_map: Map<memmap2::Mmap>,
}

impl TermDictionary {
    pub fn open<P: AsRef<Path>>(path: P) -> Result<Self, Box<dyn std::error::Error>> {
        let file = File::open(path)?;
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        let fst_map = Map::new(mmap)?;
        Ok(Self { fst_map })
    }

    pub fn get(&self, term: &str) -> Option<u64> {
        self.fst_map.get(term.as_bytes())
    }

    pub fn suggest_prefix(&self, prefix: &str, limit: usize) -> Vec<String> {
        let prefix_lower = prefix.to_lowercase();
        let prefix_matcher = Str::new(&prefix_lower).starts_with();
        let mut stream = self.fst_map.search(prefix_matcher).into_stream();

        let mut results = Vec::with_capacity(limit);
        while let Some((term_bytes, _val)) = stream.next() {
            if let Ok(term) = std::str::from_utf8(term_bytes) {
                results.push(term.to_string());
                if results.len() >= limit {
                    break;
                }
            }
        }
        results
    }

    pub fn fuzzy_terms(&self, term: &str, max_distance: u32, limit: usize) -> Vec<String> {
        let term_lower = term.to_lowercase();
        let dfa = match Levenshtein::new(&term_lower, max_distance) {
            Ok(d) => d,
            Err(_) => return Vec::new(),
        };

        let mut stream = self.fst_map.search(&dfa).into_stream();
        let mut matched = Vec::with_capacity(limit);

        while let Some((bytes, _val)) = stream.next() {
            if let Ok(s) = std::str::from_utf8(bytes)
                && s != term_lower
            {
                matched.push(s.to_string());
                if matched.len() >= limit {
                    break;
                }
            }
        }
        matched
    }
}

// ============================================================================
// Tokenizer Pipeline
// ============================================================================

pub struct TokenizerPipeline {
    stemmer: Stemmer,
    stop_words: HashSet<&'static str>,
    regex: Regex,
}

impl Default for TokenizerPipeline {
    fn default() -> Self {
        Self::new()
    }
}

impl TokenizerPipeline {
    pub fn new() -> Self {
        let stop_words: HashSet<&'static str> = [
            "a",
            "about",
            "above",
            "after",
            "again",
            "against",
            "all",
            "am",
            "an",
            "and",
            "any",
            "are",
            "aren't",
            "as",
            "at",
            "be",
            "because",
            "been",
            "before",
            "being",
            "below",
            "between",
            "both",
            "but",
            "by",
            "can't",
            "cannot",
            "could",
            "couldn't",
            "did",
            "didn't",
            "do",
            "does",
            "doesn't",
            "doing",
            "don't",
            "down",
            "during",
            "each",
            "few",
            "for",
            "from",
            "further",
            "had",
            "hadn't",
            "has",
            "hasn't",
            "have",
            "haven't",
            "having",
            "he",
            "he'd",
            "he'll",
            "he's",
            "her",
            "here",
            "here's",
            "hers",
            "herself",
            "him",
            "himself",
            "his",
            "how",
            "how's",
            "i",
            "i'd",
            "i'll",
            "i'm",
            "i've",
            "if",
            "in",
            "into",
            "is",
            "isn't",
            "it",
            "it's",
            "its",
            "itself",
            "let's",
            "me",
            "more",
            "most",
            "mustn't",
            "my",
            "myself",
            "no",
            "nor",
            "not",
            "of",
            "off",
            "on",
            "once",
            "only",
            "or",
            "other",
            "ought",
            "our",
            "ours",
            "ourselves",
            "out",
            "over",
            "own",
            "same",
            "shan't",
            "she",
            "she'd",
            "she'll",
            "she's",
            "should",
            "shouldn't",
            "so",
            "some",
            "such",
            "than",
            "that",
            "that's",
            "the",
            "their",
            "theirs",
            "them",
            "themselves",
            "then",
            "there",
            "there's",
            "these",
            "they",
            "they'd",
            "they'll",
            "they're",
            "they've",
            "this",
            "those",
            "through",
            "to",
            "too",
            "under",
            "until",
            "up",
            "very",
            "was",
            "wasn't",
            "we",
            "we'd",
            "we'll",
            "we're",
            "we've",
            "were",
            "weren't",
            "what",
            "what's",
            "when",
            "when's",
            "where",
            "where's",
            "which",
            "while",
            "who",
            "who's",
            "whom",
            "why",
            "why's",
            "with",
            "won't",
            "would",
            "wouldn't",
            "you",
            "you'd",
            "you'll",
            "you're",
            "you've",
            "your",
            "yours",
            "yourself",
            "yourselves",
        ]
        .into_iter()
        .collect();

        Self {
            stemmer: Stemmer::create(Algorithm::English),
            stop_words,
            regex: Regex::new(r"[^a-zA-Z0-9\s]+").unwrap(),
        }
    }

    pub fn tokenize(&self, text: &str) -> Vec<String> {
        let cleaned = self.regex.replace_all(text, " ").to_lowercase();
        cleaned
            .split_whitespace()
            .filter(|token| token.len() > 1 && !self.stop_words.contains(token))
            .map(|token| self.stemmer.stem(token).to_string())
            .collect()
    }
}

// ============================================================================
// Main & BM25 Scoring
// ============================================================================

fn resolve_path(env_var: &str, candidates: &[&str]) -> String {
    if let Ok(val) = std::env::var(env_var) {
        return val;
    }
    for candidate in candidates {
        if Path::new(candidate).exists() {
            return candidate.to_string();
        }
    }
    candidates[0].to_string()
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let docs_json_path = resolve_path(
        "DOCS_JSON_PATH",
        &[
            "../crawler/documents.json",
            "crawler/documents.json",
            "documents.json",
        ],
    );
    let docs_bin_path = resolve_path(
        "DOCS_PATH",
        &[
            "../crawler/documents.bin",
            "crawler/documents.bin",
            "documents.bin",
        ],
    );
    let output_bin_index_path = resolve_path("INDEX_PATH", &["index.bin", "indexer/index.bin"]);
    let output_json_index_path =
        resolve_path("INDEX_JSON_PATH", &["index.json", "indexer/index.json"]);
    let output_fst_path = resolve_path("FST_PATH", &["dictionary.fst", "indexer/dictionary.fst"]);

    // Auto-convert JSON docs to binary storage if needed
    if !Path::new(&docs_bin_path).exists() && Path::new(&docs_json_path).exists() {
        convert_json_to_bin_if_needed(&docs_json_path, &docs_bin_path)?;
    }

    let pipeline = TokenizerPipeline::new();

    println!("Opening document store from {}...", docs_bin_path);
    let start_time = Instant::now();
    let doc_store = MmapDocStore::open(&docs_bin_path)?;
    let total_docs = doc_store.doc_count();
    println!(
        "Memory-mapped {} documents in {:?}",
        total_docs,
        start_time.elapsed()
    );

    // Build inverted index and metadata from mmap document store
    println!("Indexing documents...");
    let index_start = Instant::now();
    let mut inverted_index: HashMap<String, Vec<Posting>> = HashMap::new();
    let mut doc_metadata: Vec<DocMetadata> = Vec::with_capacity(total_docs as usize);
    let mut doc_lengths: Vec<u32> = Vec::with_capacity(total_docs as usize);
    let mut total_terms: usize = 0;
    let mut url_to_id: HashMap<String, usize> = HashMap::with_capacity(total_docs as usize);
    let mut doc_links: Vec<Vec<String>> = Vec::with_capacity(total_docs as usize);

    for doc_id in 0..total_docs {
        let doc = doc_store
            .get_doc(doc_id)
            .ok_or_else(|| format!("Failed to read doc {doc_id}"))?;

        url_to_id.insert(doc.url.to_string(), doc_id as usize);
        doc_links.push(doc.links.iter().map(|s| s.to_string()).collect());

        let title_terms = pipeline.tokenize(doc.title);
        let content_terms = pipeline.tokenize(doc.content);

        let mut all_terms = Vec::with_capacity(title_terms.len() + content_terms.len());
        all_terms.extend(title_terms);
        all_terms.extend(content_terms);

        let doc_length = all_terms.len() as u32;
        total_terms += doc_length as usize;
        doc_lengths.push(doc_length);

        doc_metadata.push(DocMetadata {
            internal_id: doc_id,
            hex_id: doc.id.to_string(),
            url: doc.url.to_string(),
            title: doc.title.to_string(),
            length: doc_length,
            pagerank: 0.0,
        });

        let mut term_positions: HashMap<String, Vec<u32>> = HashMap::new();
        for (pos, term) in all_terms.into_iter().enumerate() {
            term_positions.entry(term).or_default().push(pos as u32);
        }

        for (term, positions) in term_positions {
            let tf = positions.len() as u32;
            inverted_index.entry(term).or_default().push(Posting {
                doc_id,
                term_frequency: tf,
                positions,
            });
        }
    }

    let avg_doc_length = if total_docs > 0 {
        total_terms as f64 / total_docs as f64
    } else {
        0.0
    };

    println!(
        "Indexed {} documents ({} terms) in {:?}",
        total_docs,
        total_terms,
        index_start.elapsed()
    );

    // Compute PageRank via Power Iteration
    println!("Computing PageRank via Power Iteration pass...");
    let pagerank_start = Instant::now();
    let pagerank_scores = compute_pagerank(
        total_docs as usize,
        &doc_links,
        &url_to_id,
        &PageRankConfig::default(),
    );
    for (doc_id, &score) in pagerank_scores.iter().enumerate() {
        if doc_id < doc_metadata.len() {
            doc_metadata[doc_id].pagerank = score;
        }
    }
    println!(
        "Computed PageRank for {} documents in {:?}",
        total_docs,
        pagerank_start.elapsed()
    );

    // Sort terms lexicographically for FST and binary index
    let mut sorted_terms: Vec<String> = inverted_index.keys().cloned().collect();
    sorted_terms.sort();
    sorted_terms.dedup();

    println!("\n--- Indexing Statistics ---");
    println!("Total Documents: {}", total_docs);
    println!("Unique Vocabulary Terms: {}", sorted_terms.len());
    println!("Average Document Length: {:.2} terms", avg_doc_length);

    // Save binary memory-mapped index with VByte-compressed postings
    let bin_save_start = Instant::now();
    BinaryIndexWriter::write_index(
        &output_bin_index_path,
        total_docs,
        avg_doc_length,
        &doc_lengths,
        &pagerank_scores,
        &doc_metadata,
        &sorted_terms,
        &inverted_index,
    )?;
    println!(
        "Saved binary mmap index to {} with VByte postings in {:?}",
        output_bin_index_path,
        bin_save_start.elapsed()
    );

    // Build and save Lexicon FST (Map mapping term -> term_id)
    let fst_start = Instant::now();
    let fst_file = File::create(&output_fst_path)?;
    let fst_writer = BufWriter::new(fst_file);
    let mut builder = MapBuilder::new(fst_writer)?;
    for (term_idx, term) in sorted_terms.iter().enumerate() {
        builder.insert(term.as_bytes(), term_idx as u64)?;
    }
    builder.finish()?;
    println!(
        "Compiled and saved {} terms to {} in {:?}",
        sorted_terms.len(),
        output_fst_path,
        fst_start.elapsed()
    );

    // Save legacy index.json for backward compatibility
    let json_save_start = Instant::now();
    let mut doc_meta_map: HashMap<u32, DocMetadata> = HashMap::with_capacity(doc_metadata.len());
    for meta in doc_metadata {
        doc_meta_map.insert(meta.internal_id, meta);
    }
    let index_store = IndexStore {
        total_docs,
        avg_doc_length,
        doc_meta: doc_meta_map,
        inverted_index,
    };
    let json_bytes = serde_json::to_vec_pretty(&index_store)?;
    let mut out_file = File::create(&output_json_index_path)?;
    out_file.write_all(&json_bytes)?;
    println!(
        "Saved backward-compatible {} in {:?}",
        output_json_index_path,
        json_save_start.elapsed()
    );

    // Test BM25 & PageRank Query Evaluation using memory-mapped binary index
    println!("\nVerifying retrieval against memory-mapped binary index (mmap)...");
    let mmap_index = MmapIndex::open(&output_bin_index_path)?;
    let dictionary = TermDictionary::open(&output_fst_path)?;

    let test_queries = ["search engine", "page rank algorithm", "open source"];
    for query in test_queries {
        println!("\n--- Test Query: \"{}\" ---", query);
        let results = search_combined_mmap(
            query,
            &mmap_index,
            &dictionary,
            &pipeline,
            DEFAULT_ALPHA,
            DEFAULT_EPSILON,
            5,
        );
        for (rank, (doc, score)) in results.iter().enumerate() {
            println!(
                "{}. [{:.4}] (PR: {:.6}) {} ({})",
                rank + 1,
                score,
                doc.pagerank,
                doc.title,
                doc.url
            );
        }
    }

    Ok(())
}

// ============================================================================
// PageRank & BM25 Scoring Formulas
// ============================================================================

pub const DEFAULT_ALPHA: f64 = 0.7;
pub const DEFAULT_EPSILON: f64 = 1e-6;

#[derive(Debug, Clone)]
pub struct PageRankConfig {
    pub damping: f64,
    pub max_iterations: usize,
    pub tolerance: f64,
}

impl Default for PageRankConfig {
    fn default() -> Self {
        Self {
            damping: 0.85,
            max_iterations: 100,
            tolerance: 1e-7,
        }
    }
}

pub fn resolve_url_to_id(link: &str, url_to_id: &HashMap<String, usize>) -> Option<usize> {
    if let Some(&id) = url_to_id.get(link) {
        return Some(id);
    }
    if let Some(stripped) = link.strip_suffix('/') {
        if let Some(&id) = url_to_id.get(stripped) {
            return Some(id);
        }
    } else {
        let with_slash = format!("{link}/");
        if let Some(&id) = url_to_id.get(&with_slash) {
            return Some(id);
        }
    }
    None
}

pub fn build_pagerank_graph(
    total_docs: usize,
    doc_links: &[Vec<String>],
    url_to_id: &HashMap<String, usize>,
) -> Vec<Vec<usize>> {
    let mut out_edges = Vec::with_capacity(total_docs);
    for (u, links) in doc_links.iter().enumerate() {
        let mut targets = HashSet::new();
        for link in links {
            if let Some(target_id) = resolve_url_to_id(link, url_to_id)
                && target_id != u
            {
                targets.insert(target_id);
            }
        }
        let mut target_vec: Vec<usize> = targets.into_iter().collect();
        target_vec.sort_unstable();
        out_edges.push(target_vec);
    }
    out_edges
}

pub fn power_iteration_pagerank(
    total_docs: usize,
    out_edges: &[Vec<usize>],
    config: &PageRankConfig,
) -> Vec<f64> {
    if total_docs == 0 {
        return Vec::new();
    }
    if total_docs == 1 {
        return vec![1.0];
    }

    let n = total_docs as f64;
    let damping = config.damping;
    let mut pr = vec![1.0 / n; total_docs];

    let out_degrees: Vec<usize> = out_edges.iter().map(|edges| edges.len()).collect();

    for _iter in 0..config.max_iterations {
        // Collect PageRank mass from dangling nodes (out_degree == 0)
        let dangling_sum: f64 = (0..total_docs)
            .filter(|&u| out_degrees[u] == 0)
            .map(|u| pr[u])
            .sum();

        let base_score = (1.0 - damping) / n + (damping * dangling_sum) / n;
        let mut next_pr = vec![base_score; total_docs];

        for u in 0..total_docs {
            let deg = out_degrees[u];
            if deg > 0 {
                let contribution = (damping * pr[u]) / (deg as f64);
                for &v in &out_edges[u] {
                    next_pr[v] += contribution;
                }
            }
        }

        let delta: f64 = pr
            .iter()
            .zip(next_pr.iter())
            .map(|(a, b)| (a - b).abs())
            .sum();

        pr = next_pr;

        if delta < config.tolerance {
            break;
        }
    }

    pr
}

pub fn compute_pagerank(
    total_docs: usize,
    doc_links: &[Vec<String>],
    url_to_id: &HashMap<String, usize>,
    config: &PageRankConfig,
) -> Vec<f64> {
    let out_edges = build_pagerank_graph(total_docs, doc_links, url_to_id);
    power_iteration_pagerank(total_docs, &out_edges, config)
}

#[inline]
pub fn final_score(bm25_score: f64, pagerank: f64, alpha: f64, epsilon: f64) -> f64 {
    alpha * bm25_score + (1.0 - alpha) * (pagerank + epsilon).ln()
}

#[inline]
pub fn compute_final_score(bm25_score: f64, pagerank: f64, alpha: f64, epsilon: f64) -> f64 {
    final_score(bm25_score, pagerank, alpha, epsilon)
}

#[inline]
pub fn bm25_idf(total_docs: f64, doc_freq: f64) -> f64 {
    ((total_docs - doc_freq + 0.5) / (doc_freq + 0.5) + 1.0).ln()
}

#[inline]
pub fn bm25_tf_weight(tf: f64, doc_len: f64, avg_doc_len: f64, k1: f64, b: f64) -> f64 {
    if tf <= 0.0 {
        return 0.0;
    }
    let num = tf * (k1 + 1.0);
    let denom = tf + k1 * (1.0 - b + b * (doc_len / avg_doc_len));
    num / denom
}

#[inline]
pub fn bm25_score(
    total_docs: f64,
    doc_freq: f64,
    tf: f64,
    doc_len: f64,
    avg_doc_len: f64,
    k1: f64,
    b: f64,
) -> f64 {
    bm25_idf(total_docs, doc_freq) * bm25_tf_weight(tf, doc_len, avg_doc_len, k1, b)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedQuery {
    pub phrases: Vec<Vec<String>>,
    pub unquoted_terms: Vec<String>,
}

impl ParsedQuery {
    pub fn all_terms(&self) -> Vec<String> {
        let mut terms = Vec::new();
        for phrase in &self.phrases {
            for term in phrase {
                if !terms.contains(term) {
                    terms.push(term.clone());
                }
            }
        }
        for term in &self.unquoted_terms {
            if !terms.contains(term) {
                terms.push(term.clone());
            }
        }
        terms
    }
}

pub fn parse_query(query: &str, pipeline: &TokenizerPipeline) -> ParsedQuery {
    let mut phrases = Vec::new();
    let mut unquoted_text = String::new();

    let mut in_quote = false;
    let mut current_phrase = String::new();

    for ch in query.chars() {
        if ch == '"' {
            if in_quote {
                let tokens = pipeline.tokenize(&current_phrase);
                if !tokens.is_empty() {
                    phrases.push(tokens);
                }
                current_phrase.clear();
                in_quote = false;
            } else {
                in_quote = true;
            }
        } else if in_quote {
            current_phrase.push(ch);
        } else {
            unquoted_text.push(ch);
        }
    }

    if in_quote && !current_phrase.is_empty() {
        let tokens = pipeline.tokenize(&current_phrase);
        if !tokens.is_empty() {
            phrases.push(tokens);
        }
    }

    let unquoted_terms = pipeline.tokenize(&unquoted_text);

    ParsedQuery {
        phrases,
        unquoted_terms,
    }
}

pub fn phrase_matches(positions_list: &[&[u32]]) -> bool {
    if positions_list.is_empty() {
        return true;
    }
    if positions_list.len() == 1 {
        return !positions_list[0].is_empty();
    }
    let mut current_starts: Vec<u32> = positions_list[0].to_vec();
    for (offset, next_positions) in positions_list.iter().skip(1).enumerate() {
        let expected_offset = (offset + 1) as u32;
        let mut next_starts = Vec::new();
        let mut i = 0;
        let mut j = 0;
        while i < current_starts.len() && j < next_positions.len() {
            let target = current_starts[i].saturating_add(expected_offset);
            if next_positions[j] == target {
                next_starts.push(current_starts[i]);
                i += 1;
                j += 1;
            } else if next_positions[j] < target {
                j += 1;
            } else {
                i += 1;
            }
        }
        current_starts = next_starts;
        if current_starts.is_empty() {
            return false;
        }
    }
    !current_starts.is_empty()
}

pub fn search_combined_mmap<'a>(
    query: &str,
    index: &'a MmapIndex,
    dictionary: &TermDictionary,
    pipeline: &TokenizerPipeline,
    alpha: f64,
    epsilon: f64,
    top_k: usize,
) -> Vec<(DocMetaRef<'a>, f64)> {
    if top_k == 0 {
        return Vec::new();
    }
    let k1 = 1.5;
    let b = 0.75;
    let parsed_query = parse_query(query, pipeline);
    let all_terms = parsed_query.all_terms();
    if all_terms.is_empty() {
        return Vec::new();
    }

    // Filter documents by phrase requirements if any phrases exist
    let mut phrase_matching_docs: Option<HashSet<u32>> = None;

    for phrase in &parsed_query.phrases {
        if phrase.is_empty() {
            continue;
        }
        let mut term_postings = Vec::with_capacity(phrase.len());
        let mut all_found = true;
        for term in phrase {
            if let Some(term_idx) = dictionary.get(term)
                && let Some(entry) = index.get_term_entry(term_idx as usize)
            {
                let slice = index.get_postings_slice(&entry);
                let iter = PostingsIterator::new(slice, entry.doc_freq as usize);
                let map: HashMap<u32, Vec<u32>> = iter.map(|p| (p.doc_id, p.positions)).collect();
                term_postings.push(map);
            } else {
                all_found = false;
                break;
            }
        }

        if !all_found {
            return Vec::new();
        }

        let mut matching_in_phrase = HashSet::new();
        if let Some(first_map) = term_postings.first() {
            for (&doc_id, first_positions) in first_map {
                let mut doc_positions: Vec<&[u32]> = Vec::with_capacity(term_postings.len());
                doc_positions.push(first_positions.as_slice());
                let mut in_all = true;
                for next_map in &term_postings[1..] {
                    if let Some(pos) = next_map.get(&doc_id) {
                        doc_positions.push(pos.as_slice());
                    } else {
                        in_all = false;
                        break;
                    }
                }
                if in_all && phrase_matches(&doc_positions) {
                    matching_in_phrase.insert(doc_id);
                }
            }
        }

        phrase_matching_docs = match phrase_matching_docs {
            None => Some(matching_in_phrase),
            Some(existing) => Some(
                existing
                    .intersection(&matching_in_phrase)
                    .copied()
                    .collect(),
            ),
        };

        if let Some(ref docs) = phrase_matching_docs
            && docs.is_empty()
        {
            return Vec::new();
        }
    }

    let n = index.total_docs as f64;
    let pr_max = if alpha < 1.0 {
        (1.0 - alpha) * (1.0 + epsilon).ln()
    } else {
        0.0
    };

    // Initialize WAND cursors for all query terms
    let mut cursors: Vec<WandPostingCursor<'a>> = Vec::with_capacity(all_terms.len());
    for term in &all_terms {
        if let Some(term_idx) = dictionary.get(term)
            && let Some(entry) = index.get_term_entry(term_idx as usize)
        {
            if entry.doc_freq == 0 {
                continue;
            }
            let n_q = entry.doc_freq as f64;
            let idf = bm25_idf(n, n_q);
            // Universal upper bound on term score contribution
            let max_score = alpha * idf * (k1 + 1.0);
            let slice = index.get_postings_slice(&entry);
            let cursor = WandPostingCursor::new(slice, entry.doc_freq as usize, idf, max_score);
            if cursor.has_more {
                cursors.push(cursor);
            }
        }
    }

    if cursors.is_empty() {
        return Vec::new();
    }

    let mut heap: BinaryHeap<ScoredDoc> = BinaryHeap::with_capacity(top_k + 1);
    let mut threshold = f64::NEG_INFINITY;

    while !cursors.is_empty() {
        // Sort cursors by current_doc_id
        cursors.sort_unstable_by_key(|c| c.current_doc_id);

        // Find pivot term where accumulated upper bound > threshold - pr_max
        let score_limit = threshold - pr_max;
        let mut accum = 0.0;
        let mut pivot_idx = None;

        for (i, c) in cursors.iter().enumerate() {
            accum += c.max_score;
            if accum > score_limit {
                pivot_idx = Some(i);
                break;
            }
        }

        let Some(p) = pivot_idx else {
            // No remaining document can beat the current threshold
            break;
        };

        let pivot_doc = cursors[p].current_doc_id;

        if cursors[0].current_doc_id == pivot_doc {
            let target_doc = pivot_doc;
            let is_allowed = phrase_matching_docs
                .as_ref()
                .is_none_or(|docs| docs.contains(&target_doc));

            if is_allowed {
                let doc_len = index.get_doc_length(target_doc) as f64;
                let mut bm25_total = 0.0;

                for c in cursors.iter_mut() {
                    if c.current_doc_id == target_doc {
                        let tf = c.current_tf as f64;
                        let term_score =
                            c.idf * bm25_tf_weight(tf, doc_len, index.avg_doc_length, k1, b);
                        bm25_total += term_score;
                        c.read_next();
                    }
                }

                let pr = index.get_pagerank(target_doc);
                let score = final_score(bm25_total, pr, alpha, epsilon);

                if heap.len() < top_k {
                    heap.push(ScoredDoc {
                        doc_id: target_doc,
                        score,
                    });
                    if heap.len() == top_k {
                        threshold = heap.peek().unwrap().score;
                    }
                } else if score > threshold {
                    heap.pop();
                    heap.push(ScoredDoc {
                        doc_id: target_doc,
                        score,
                    });
                    threshold = heap.peek().unwrap().score;
                }
            } else {
                for c in cursors.iter_mut() {
                    if c.current_doc_id == target_doc {
                        c.read_next();
                    }
                }
            }
        } else {
            // Skip uncompetitive documents: advance cursor 0 to at least pivot_doc
            cursors[0].advance_to(pivot_doc);
        }

        cursors.retain(|c| c.has_more);
    }

    let mut ranked: Vec<ScoredDoc> = heap.into_vec();
    ranked.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.doc_id.cmp(&b.doc_id))
    });

    ranked
        .into_iter()
        .filter_map(|hit| index.get_doc_meta(hit.doc_id).map(|meta| (meta, hit.score)))
        .collect()
}

pub fn search_bm25_mmap<'a>(
    query: &str,
    index: &'a MmapIndex,
    dictionary: &TermDictionary,
    pipeline: &TokenizerPipeline,
    top_k: usize,
) -> Vec<(DocMetaRef<'a>, f64)> {
    search_combined_mmap(
        query,
        index,
        dictionary,
        pipeline,
        1.0,
        DEFAULT_EPSILON,
        top_k,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------------
    // VByte Encoding & Decoding Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_vbyte_roundtrip_boundaries() {
        let test_values = [
            0u32,
            1,
            63,
            127, // 1 byte boundary (0x7F)
            128, // 2 byte boundary (0x80)
            129,
            255,
            256,
            16383, // 2 byte max ((1 << 14) - 1)
            16384, // 3 byte boundary (1 << 14)
            65535,
            65536,
            2097151,   // 3 byte max ((1 << 21) - 1)
            2097152,   // 4 byte boundary (1 << 21)
            268435455, // 4 byte max ((1 << 28) - 1)
            268435456, // 5 byte boundary (1 << 28)
            u32::MAX - 1,
            u32::MAX,
        ];

        for &val in &test_values {
            let mut buf = Vec::new();
            encode_vbyte(val, &mut buf);

            // Verify encoded length expectations
            let expected_bytes = match val {
                0..=0x7F => 1,
                0x80..=0x3FFF => 2,
                0x4000..=0x1F_FFFF => 3,
                0x20_0000..=0xFFF_FFFF => 4,
                _ => 5,
            };
            assert_eq!(
                buf.len(),
                expected_bytes,
                "Unexpected byte count for value {}",
                val
            );

            let mut offset = 0;
            let decoded = decode_vbyte(&buf, &mut offset);
            assert_eq!(decoded, Some(val), "Failed roundtrip for value {}", val);
            assert_eq!(
                offset,
                buf.len(),
                "Did not consume full buffer for value {}",
                val
            );
        }
    }

    #[test]
    fn test_vbyte_roundtrip_sequential_stream() {
        let values = [
            0u32,
            1,
            42,
            127,
            128,
            500,
            16384,
            99999,
            1_000_000,
            u32::MAX,
        ];
        let mut buf = Vec::new();

        for &v in &values {
            encode_vbyte(v, &mut buf);
        }

        let mut offset = 0;
        let mut decoded = Vec::new();
        while let Some(val) = decode_vbyte(&buf, &mut offset) {
            decoded.push(val);
        }

        assert_eq!(decoded, values);
        assert_eq!(offset, buf.len());
    }

    #[test]
    fn test_vbyte_decode_truncated_and_invalid() {
        let mut offset = 0;
        // Empty slice
        assert_eq!(decode_vbyte(&[], &mut offset), None);

        // Continuation bit set on single byte without terminating byte
        offset = 0;
        assert_eq!(decode_vbyte(&[0x80], &mut offset), None);

        // Incomplete sequence
        offset = 0;
        assert_eq!(decode_vbyte(&[0x81, 0x82], &mut offset), None);

        // Overflow: more than 5 bytes with continuation bit set (shift > 35)
        offset = 0;
        let malformed = [0x80, 0x80, 0x80, 0x80, 0x80, 0x80];
        assert_eq!(decode_vbyte(&malformed, &mut offset), None);
    }

    // ------------------------------------------------------------------------
    // Delta Decoding & PostingsIterator Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_delta_decoding_roundtrip() {
        let original_postings = vec![
            Posting {
                doc_id: 10,
                term_frequency: 1,
                positions: vec![3],
            },
            Posting {
                doc_id: 15,
                term_frequency: 3,
                positions: vec![1, 5, 12],
            },
            Posting {
                doc_id: 42,
                term_frequency: 2,
                positions: vec![0, 7],
            },
            Posting {
                doc_id: 100,
                term_frequency: 4,
                positions: vec![2, 4, 6, 8],
            },
            Posting {
                doc_id: 105,
                term_frequency: 1,
                positions: vec![100],
            },
        ];

        let mut buf = Vec::new();
        encode_postings(&original_postings, &mut buf);

        let iter = PostingsIterator::new(&buf, original_postings.len());
        let decoded_postings: Vec<Posting> = iter.collect();

        assert_eq!(decoded_postings, original_postings);
    }

    #[test]
    fn test_delta_decoding_first_doc_zero() {
        let original_postings = vec![
            Posting {
                doc_id: 0,
                term_frequency: 3,
                positions: vec![0, 1, 2],
            },
            Posting {
                doc_id: 1,
                term_frequency: 2,
                positions: vec![5, 10],
            },
            Posting {
                doc_id: 2,
                term_frequency: 1,
                positions: vec![20],
            },
        ];

        let mut buf = Vec::new();
        encode_postings(&original_postings, &mut buf);

        let iter = PostingsIterator::new(&buf, original_postings.len());
        let decoded_postings: Vec<Posting> = iter.collect();

        assert_eq!(decoded_postings, original_postings);
    }

    #[test]
    fn test_delta_decoding_large_gaps() {
        let original_postings = vec![
            Posting {
                doc_id: 5,
                term_frequency: 1,
                positions: vec![10],
            },
            Posting {
                doc_id: 1_000,
                term_frequency: 2,
                positions: vec![50, 500],
            },
            Posting {
                doc_id: 100_000,
                term_frequency: 2,
                positions: vec![1_000, 20_000],
            },
            Posting {
                doc_id: 5_000_000,
                term_frequency: 3,
                positions: vec![100, 200_000, 1_000_000],
            },
        ];

        let mut buf = Vec::new();
        encode_postings(&original_postings, &mut buf);

        let iter = PostingsIterator::new(&buf, original_postings.len());
        let decoded: Vec<Posting> = iter.collect();

        assert_eq!(decoded, original_postings);
    }

    #[test]
    fn test_delta_decoding_empty_and_single_posting() {
        // Empty postings
        let empty_iter = PostingsIterator::new(&[], 0);
        let empty_results: Vec<Posting> = empty_iter.collect();
        assert!(empty_results.is_empty());

        // Single posting
        let single = vec![Posting {
            doc_id: 777,
            term_frequency: 2,
            positions: vec![42, 99],
        }];
        let mut buf = Vec::new();
        encode_postings(&single, &mut buf);

        let single_iter = PostingsIterator::new(&buf, single.len());
        let single_results: Vec<Posting> = single_iter.collect();
        assert_eq!(single_results, single);
    }

    #[test]
    fn test_delta_decoding_direct_accumulator() {
        // Test that deltas [10, 5, 20] decode into absolute doc_ids [10, 15, 35]
        // and position deltas decode into absolute word offsets
        let mut buf = Vec::new();
        encode_vbyte(10, &mut buf); // doc_id delta: 10
        encode_vbyte(2, &mut buf); // tf: 2
        encode_vbyte(5, &mut buf); // pos_delta: 5 -> pos: 5
        encode_vbyte(3, &mut buf); // pos_delta: 3 -> pos: 8
        encode_vbyte(5, &mut buf); // doc_id delta: 5 -> doc_id: 15
        encode_vbyte(1, &mut buf); // tf: 1
        encode_vbyte(12, &mut buf); // pos_delta: 12 -> pos: 12
        encode_vbyte(20, &mut buf); // doc_id delta: 20 -> doc_id: 35
        encode_vbyte(3, &mut buf); // tf: 3
        encode_vbyte(1, &mut buf); // pos_delta: 1 -> pos: 1
        encode_vbyte(4, &mut buf); // pos_delta: 4 -> pos: 5
        encode_vbyte(10, &mut buf); // pos_delta: 10 -> pos: 15

        let iter = PostingsIterator::new(&buf, 3);
        let decoded: Vec<Posting> = iter.collect();

        assert_eq!(
            decoded,
            vec![
                Posting {
                    doc_id: 10,
                    term_frequency: 2,
                    positions: vec![5, 8],
                },
                Posting {
                    doc_id: 15,
                    term_frequency: 1,
                    positions: vec![12],
                },
                Posting {
                    doc_id: 35,
                    term_frequency: 3,
                    positions: vec![1, 5, 15],
                },
            ]
        );
    }

    // ------------------------------------------------------------------------
    // Phrase Matching & Query Parsing Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_phrase_matches_basic() {
        // Single term
        assert!(phrase_matches(&[&[1, 5, 10]]));
        assert!(!phrase_matches(&[&[]]));

        // Two terms consecutive: pos 4 in first, pos 5 in second
        let pos1 = [2, 4, 10];
        let pos2 = [5, 20];
        assert!(phrase_matches(&[&pos1, &pos2]));

        // Two terms non-consecutive
        let pos1_fail = [2, 4, 10];
        let pos2_fail = [7, 20];
        assert!(!phrase_matches(&[&pos1_fail, &pos2_fail]));

        // Two terms reverse order
        let pos1_rev = [5];
        let pos2_rev = [4];
        assert!(!phrase_matches(&[&pos1_rev, &pos2_rev]));

        // Three terms consecutive: 10, 11, 12
        let p1 = [1, 10, 50];
        let p2 = [2, 11, 60];
        let p3 = [3, 12, 70];
        assert!(phrase_matches(&[&p1, &p2, &p3]));

        // Three terms where third term misses
        let p1_m = [10, 50];
        let p2_m = [11, 60];
        let p3_m_fail = [13, 70];
        assert!(!phrase_matches(&[&p1_m, &p2_m, &p3_m_fail]));
    }

    #[test]
    fn test_parse_query_variations() {
        let pipeline = TokenizerPipeline::new();

        // Plain unquoted query
        let q1 = parse_query("distributed systems", &pipeline);
        assert!(q1.phrases.is_empty());
        assert_eq!(q1.unquoted_terms, vec!["distribut", "system"]);

        // Pure quoted query
        let q2 = parse_query("\"distributed systems\"", &pipeline);
        assert_eq!(q2.phrases, vec![vec!["distribut", "system"]]);
        assert!(q2.unquoted_terms.is_empty());

        // Mixed quoted and unquoted
        let q3 = parse_query("rust \"distributed systems\" fast", &pipeline);
        assert_eq!(q3.phrases, vec![vec!["distribut", "system"]]);
        assert_eq!(q3.unquoted_terms, vec!["rust", "fast"]);

        // Multiple quoted phrases
        let q4 = parse_query("\"distributed systems\" \"fault tolerance\"", &pipeline);
        assert_eq!(
            q4.phrases,
            vec![vec!["distribut", "system"], vec!["fault", "toler"]]
        );
        assert!(q4.unquoted_terms.is_empty());

        // Unclosed quote at end
        let q5 = parse_query("\"distributed systems", &pipeline);
        assert_eq!(q5.phrases, vec![vec!["distribut", "system"]]);
        assert!(q5.unquoted_terms.is_empty());
    }

    // ------------------------------------------------------------------------
    // BM25 Scoring Arithmetic Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_bm25_idf_known_values() {
        // N = 100, n_q = 1: idf = ln((100 - 1 + 0.5)/(1 + 0.5) + 1.0) = ln(99.5/1.5 + 1.0)
        let idf_rare = bm25_idf(100.0, 1.0);
        let expected_rare = (99.5 / 1.5 + 1.0_f64).ln();
        assert!((idf_rare - expected_rare).abs() < 1e-10);
        assert!((idf_rare - 4.209655).abs() < 1e-5);

        // N = 100, n_q = 50: idf = ln((100 - 50 + 0.5)/(50 + 0.5) + 1.0) = ln(1.0 + 1.0) = ln(2.0)
        let idf_half = bm25_idf(100.0, 50.0);
        let expected_half = 2.0_f64.ln();
        assert!((idf_half - expected_half).abs() < 1e-10);
        assert!((idf_half - 0.693147).abs() < 1e-5);
    }

    #[test]
    fn test_bm25_idf_monotonicity_and_positivity() {
        let total_docs = 1000.0;
        // As document frequency increases, IDF must strictly decrease
        let idf_1 = bm25_idf(total_docs, 1.0);
        let idf_10 = bm25_idf(total_docs, 10.0);
        let idf_100 = bm25_idf(total_docs, 100.0);
        let idf_1000 = bm25_idf(total_docs, 1000.0);

        assert!(idf_1 > idf_10);
        assert!(idf_10 > idf_100);
        assert!(idf_100 > idf_1000);

        // Even when a term appears in every document (n_q = total_docs), IDF is strictly positive
        assert!(idf_1000 > 0.0);
    }

    #[test]
    fn test_bm25_tf_weight_properties() {
        let k1 = 1.5;
        let b = 0.75;
        let avg_doc_len = 100.0;

        // When tf == 0, weight must be 0
        assert_eq!(bm25_tf_weight(0.0, avg_doc_len, avg_doc_len, k1, b), 0.0);

        // When doc_len == avg_doc_len and tf == 1.0:
        // num = 1.0 * (k1 + 1.0) = 2.5
        // denom = 1.0 + k1 * (1 - b + b * 1) = 1.0 + 1.5 = 2.5
        // weight is exactly 1.0
        let weight_standard = bm25_tf_weight(1.0, avg_doc_len, avg_doc_len, k1, b);
        assert!((weight_standard - 1.0).abs() < 1e-10);

        // Monotonic increase with term frequency:
        let weight_tf1 = bm25_tf_weight(1.0, avg_doc_len, avg_doc_len, k1, b);
        let weight_tf2 = bm25_tf_weight(2.0, avg_doc_len, avg_doc_len, k1, b);
        let weight_tf5 = bm25_tf_weight(5.0, avg_doc_len, avg_doc_len, k1, b);
        let weight_tf100 = bm25_tf_weight(100.0, avg_doc_len, avg_doc_len, k1, b);

        assert!(weight_tf1 < weight_tf2);
        assert!(weight_tf2 < weight_tf5);
        assert!(weight_tf5 < weight_tf100);

        // Upper bounded by (k1 + 1.0) = 2.5
        assert!(weight_tf100 < 2.5);
    }

    #[test]
    fn test_bm25_document_length_penalty() {
        let k1 = 1.5;
        let b = 0.75;
        let avg_doc_len = 100.0;
        let tf = 2.0;

        let short_doc_weight = bm25_tf_weight(tf, 50.0, avg_doc_len, k1, b);
        let normal_doc_weight = bm25_tf_weight(tf, 100.0, avg_doc_len, k1, b);
        let long_doc_weight = bm25_tf_weight(tf, 200.0, avg_doc_len, k1, b);

        // Shorter documents receive higher term weight than longer documents with the same TF
        assert!(short_doc_weight > normal_doc_weight);
        assert!(normal_doc_weight > long_doc_weight);
    }

    #[test]
    fn test_bm25_score_computation() {
        let total_docs = 500.0;
        let doc_freq = 10.0;
        let tf = 3.0;
        let doc_len = 120.0;
        let avg_doc_len = 100.0;
        let k1 = 1.5;
        let b = 0.75;

        let idf = bm25_idf(total_docs, doc_freq);
        let tf_weight = bm25_tf_weight(tf, doc_len, avg_doc_len, k1, b);
        let score = bm25_score(total_docs, doc_freq, tf, doc_len, avg_doc_len, k1, b);

        assert_eq!(score, idf * tf_weight);
        assert!(score > 0.0);
    }

    // ------------------------------------------------------------------------
    // PageRank & FinalScore Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_pagerank_two_nodes_symmetric() {
        // 0 -> 1 and 1 -> 0
        let edges = vec![vec![1], vec![0]];
        let config = PageRankConfig::default();
        let pr = power_iteration_pagerank(2, &edges, &config);

        assert_eq!(pr.len(), 2);
        assert!((pr[0] - 0.5).abs() < 1e-6);
        assert!((pr[1] - 0.5).abs() < 1e-6);
        assert!((pr[0] + pr[1] - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_pagerank_three_nodes_flow() {
        // 0 -> 1, 0 -> 2
        // 1 -> 2
        // 2 -> 0
        // Node 2 has highest incoming authority
        let edges = vec![vec![1, 2], vec![2], vec![0]];
        let config = PageRankConfig::default();
        let pr = power_iteration_pagerank(3, &edges, &config);

        assert_eq!(pr.len(), 3);
        let sum: f64 = pr.iter().sum();
        assert!((sum - 1.0).abs() < 1e-6);
        assert!(pr[2] > pr[0]);
        assert!(pr[2] > pr[1]);
    }

    #[test]
    fn test_pagerank_dangling_node_mass_preservation() {
        // 0 -> 1; 1 has no outgoing links (dangling)
        let edges = vec![vec![1], vec![]];
        let config = PageRankConfig::default();
        let pr = power_iteration_pagerank(2, &edges, &config);

        assert_eq!(pr.len(), 2);
        let sum: f64 = pr.iter().sum();
        assert!((sum - 1.0).abs() < 1e-6);
        // Node 1 receives incoming link from 0, so pr[1] > pr[0]
        assert!(pr[1] > pr[0]);
    }

    #[test]
    fn test_pagerank_empty_and_single_node() {
        let config = PageRankConfig::default();
        assert_eq!(power_iteration_pagerank(0, &[], &config), Vec::<f64>::new());
        assert_eq!(power_iteration_pagerank(1, &[vec![]], &config), vec![1.0]);
    }

    #[test]
    fn test_final_score_formula() {
        let bm25: f64 = 4.0;
        let pr: f64 = 0.05;
        let alpha: f64 = 0.7;
        let epsilon: f64 = 1e-6;

        let expected = alpha * bm25 + (1.0 - alpha) * (pr + epsilon).ln();
        let computed = final_score(bm25, pr, alpha, epsilon);

        assert!((computed - expected).abs() < 1e-10);
    }

    #[test]
    fn test_final_score_alpha_bounds() {
        let bm25: f64 = 5.5;
        let pr: f64 = 0.02;
        let epsilon: f64 = 1e-6;

        // When alpha = 1.0, score must equal pure BM25
        let score_pure_bm25 = final_score(bm25, pr, 1.0, epsilon);
        assert!((score_pure_bm25 - bm25).abs() < 1e-10);

        // When alpha = 0.0, score must equal pure log(PageRank + epsilon)
        let score_pure_pr = final_score(bm25, pr, 0.0, epsilon);
        assert!((score_pure_pr - (pr + epsilon).ln()).abs() < 1e-10);
    }

    #[test]
    fn test_binary_index_pagerank_roundtrip() {
        let test_path = "target/test_pagerank_index.bin";
        let total_docs = 3;
        let avg_doc_length = 50.0;
        let doc_lengths = vec![40, 50, 60];
        let pagerank = vec![0.2, 0.5, 0.3];
        let doc_metadata = vec![
            DocMetadata {
                internal_id: 0,
                hex_id: "000001".to_string(),
                url: "https://example.com/1".to_string(),
                title: "Doc 1".to_string(),
                length: 40,
                pagerank: 0.2,
            },
            DocMetadata {
                internal_id: 1,
                hex_id: "000002".to_string(),
                url: "https://example.com/2".to_string(),
                title: "Doc 2".to_string(),
                length: 50,
                pagerank: 0.5,
            },
            DocMetadata {
                internal_id: 2,
                hex_id: "000003".to_string(),
                url: "https://example.com/3".to_string(),
                title: "Doc 3".to_string(),
                length: 60,
                pagerank: 0.3,
            },
        ];
        let sorted_terms = vec!["term".to_string()];
        let mut inverted_index = HashMap::new();
        inverted_index.insert(
            "term".to_string(),
            vec![Posting {
                doc_id: 0,
                term_frequency: 1,
                positions: vec![0],
            }],
        );

        BinaryIndexWriter::write_index(
            test_path,
            total_docs,
            avg_doc_length,
            &doc_lengths,
            &pagerank,
            &doc_metadata,
            &sorted_terms,
            &inverted_index,
        )
        .expect("write_index failed");

        let mmap_index = MmapIndex::open(test_path).expect("open failed");
        assert_eq!(mmap_index.total_docs, total_docs);
        assert!((mmap_index.get_pagerank(0) - 0.2).abs() < 1e-9);
        assert!((mmap_index.get_pagerank(1) - 0.5).abs() < 1e-9);
        assert!((mmap_index.get_pagerank(2) - 0.3).abs() < 1e-9);

        let meta1 = mmap_index.get_doc_meta(1).expect("meta 1 missing");
        assert!((meta1.pagerank - 0.5).abs() < 1e-9);
        assert_eq!(meta1.title, "Doc 2");

        let _ = std::fs::remove_file(test_path);
    }

    #[test]
    fn test_quoted_query_search_integration() {
        let test_index_path = "target/test_quoted_search_index.bin";
        let test_fst_path = "target/test_quoted_search_dict.fst";

        let total_docs = 3;
        let avg_doc_length = 10.0;
        let doc_lengths = vec![10, 10, 10];
        let pagerank = vec![0.33, 0.33, 0.34];
        let doc_metadata = vec![
            DocMetadata {
                internal_id: 0,
                hex_id: "doc0".to_string(),
                url: "https://example.com/0".to_string(),
                title: "Distributed Systems Intro".to_string(),
                length: 10,
                pagerank: 0.33,
            },
            DocMetadata {
                internal_id: 1,
                hex_id: "doc1".to_string(),
                url: "https://example.com/1".to_string(),
                title: "Systems That Are Distributed".to_string(),
                length: 10,
                pagerank: 0.33,
            },
            DocMetadata {
                internal_id: 2,
                hex_id: "doc2".to_string(),
                url: "https://example.com/2".to_string(),
                title: "Unrelated Topic".to_string(),
                length: 10,
                pagerank: 0.34,
            },
        ];

        // Doc 0: "distribut" at pos 0, "system" at pos 1 (consecutive)
        // Doc 1: "system" at pos 0, "distribut" at pos 4 (non-consecutive and reversed)
        let mut inverted_index = HashMap::new();
        inverted_index.insert(
            "distribut".to_string(),
            vec![
                Posting {
                    doc_id: 0,
                    term_frequency: 1,
                    positions: vec![0],
                },
                Posting {
                    doc_id: 1,
                    term_frequency: 1,
                    positions: vec![4],
                },
            ],
        );
        inverted_index.insert(
            "system".to_string(),
            vec![
                Posting {
                    doc_id: 0,
                    term_frequency: 1,
                    positions: vec![1],
                },
                Posting {
                    doc_id: 1,
                    term_frequency: 1,
                    positions: vec![0],
                },
            ],
        );

        let mut sorted_terms = vec!["distribut".to_string(), "system".to_string()];
        sorted_terms.sort();

        BinaryIndexWriter::write_index(
            test_index_path,
            total_docs,
            avg_doc_length,
            &doc_lengths,
            &pagerank,
            &doc_metadata,
            &sorted_terms,
            &inverted_index,
        )
        .expect("write_index failed");

        let fst_file = File::create(test_fst_path).expect("create fst failed");
        let fst_writer = BufWriter::new(fst_file);
        let mut builder = MapBuilder::new(fst_writer).expect("mapbuilder failed");
        for (term_idx, term) in sorted_terms.iter().enumerate() {
            builder
                .insert(term.as_bytes(), term_idx as u64)
                .expect("insert term");
        }
        builder.finish().expect("finish fst");

        let mmap_index = MmapIndex::open(test_index_path).expect("open index failed");
        let dictionary = TermDictionary::open(test_fst_path).expect("open dict failed");
        let pipeline = TokenizerPipeline::new();

        // 1. Quoted query: "distributed systems" -> only doc 0 matches
        let quoted_res = search_combined_mmap(
            "\"distributed systems\"",
            &mmap_index,
            &dictionary,
            &pipeline,
            1.0,
            DEFAULT_EPSILON,
            10,
        );
        assert_eq!(quoted_res.len(), 1);
        assert_eq!(quoted_res[0].0.hex_id, "doc0");

        // 2. Reversed quoted query: "systems distributed" -> 0 hits
        let rev_res = search_combined_mmap(
            "\"systems distributed\"",
            &mmap_index,
            &dictionary,
            &pipeline,
            1.0,
            DEFAULT_EPSILON,
            10,
        );
        assert_eq!(rev_res.len(), 0);

        // 3. Unquoted query: distributed systems -> both doc 0 and doc 1 match
        let unquoted_res = search_combined_mmap(
            "distributed systems",
            &mmap_index,
            &dictionary,
            &pipeline,
            1.0,
            DEFAULT_EPSILON,
            10,
        );
        assert_eq!(unquoted_res.len(), 2);

        let _ = std::fs::remove_file(test_index_path);
        let _ = std::fs::remove_file(test_fst_path);
    }

    #[test]
    fn test_wand_posting_cursor_advance_and_read() {
        let mut buf = Vec::new();
        // doc 5, tf 1, pos [0]
        encode_vbyte(5, &mut buf);
        encode_vbyte(1, &mut buf);
        encode_vbyte(0, &mut buf);

        // doc 12 (delta 7), tf 2, pos [3, 8]
        encode_vbyte(7, &mut buf);
        encode_vbyte(2, &mut buf);
        encode_vbyte(3, &mut buf);
        encode_vbyte(5, &mut buf);

        // doc 30 (delta 18), tf 1, pos [10]
        encode_vbyte(18, &mut buf);
        encode_vbyte(1, &mut buf);
        encode_vbyte(10, &mut buf);

        // doc 45 (delta 15), tf 1, pos [2]
        encode_vbyte(15, &mut buf);
        encode_vbyte(1, &mut buf);
        encode_vbyte(2, &mut buf);

        let mut cursor = WandPostingCursor::new(&buf, 4, 2.0, 5.0);
        assert!(cursor.has_more);
        assert_eq!(cursor.current_doc_id, 5);
        assert_eq!(cursor.current_tf, 1);

        // Advance to doc 20 -> should land on doc 30
        assert!(cursor.advance_to(20));
        assert_eq!(cursor.current_doc_id, 30);
        assert_eq!(cursor.current_tf, 1);

        // Advance to 30 -> stays on 30
        assert!(cursor.advance_to(30));
        assert_eq!(cursor.current_doc_id, 30);

        // Advance to 40 -> lands on 45
        assert!(cursor.advance_to(40));
        assert_eq!(cursor.current_doc_id, 45);

        // Advance past all -> ends
        assert!(!cursor.advance_to(50));
        assert!(!cursor.has_more);
    }

    #[test]
    fn test_wand_multi_term_top_k_pruning() {
        let test_index_path = "target/test_wand_prune_index.bin";
        let test_fst_path = "target/test_wand_prune_dict.fst";

        let total_docs = 6;
        let avg_doc_length = 20.0;
        let doc_lengths = vec![20; 6];
        let pagerank = vec![1.0 / 6.0; 6];
        let doc_metadata: Vec<DocMetadata> = (0..6)
            .map(|i| DocMetadata {
                internal_id: i,
                hex_id: format!("doc{}", i),
                url: format!("https://example.com/{}", i),
                title: format!("Doc Title {}", i),
                length: 20,
                pagerank: 1.0 / 6.0,
            })
            .collect();

        // 3 terms:
        // "alpha": doc 0 (tf=5), doc 1 (tf=5), doc 2 (tf=1)
        // "beta": doc 0 (tf=5), doc 1 (tf=4), doc 3 (tf=1)
        // "gamma": doc 0 (tf=5), doc 4 (tf=1), doc 5 (tf=1)
        let mut inverted_index = HashMap::new();
        inverted_index.insert(
            "alpha".to_string(),
            vec![
                Posting {
                    doc_id: 0,
                    term_frequency: 5,
                    positions: vec![0, 1, 2, 3, 4],
                },
                Posting {
                    doc_id: 1,
                    term_frequency: 5,
                    positions: vec![0, 1, 2, 3, 4],
                },
                Posting {
                    doc_id: 2,
                    term_frequency: 1,
                    positions: vec![0],
                },
            ],
        );
        inverted_index.insert(
            "beta".to_string(),
            vec![
                Posting {
                    doc_id: 0,
                    term_frequency: 5,
                    positions: vec![0, 1, 2, 3, 4],
                },
                Posting {
                    doc_id: 1,
                    term_frequency: 4,
                    positions: vec![0, 1, 2, 3],
                },
                Posting {
                    doc_id: 3,
                    term_frequency: 1,
                    positions: vec![0],
                },
            ],
        );
        inverted_index.insert(
            "gamma".to_string(),
            vec![
                Posting {
                    doc_id: 0,
                    term_frequency: 5,
                    positions: vec![0, 1, 2, 3, 4],
                },
                Posting {
                    doc_id: 4,
                    term_frequency: 1,
                    positions: vec![0],
                },
                Posting {
                    doc_id: 5,
                    term_frequency: 1,
                    positions: vec![0],
                },
            ],
        );

        let mut sorted_terms = vec!["alpha".to_string(), "beta".to_string(), "gamma".to_string()];
        sorted_terms.sort();

        BinaryIndexWriter::write_index(
            test_index_path,
            total_docs,
            avg_doc_length,
            &doc_lengths,
            &pagerank,
            &doc_metadata,
            &sorted_terms,
            &inverted_index,
        )
        .expect("write_index failed");

        let fst_file = File::create(test_fst_path).expect("create fst failed");
        let fst_writer = BufWriter::new(fst_file);
        let mut builder = MapBuilder::new(fst_writer).expect("mapbuilder failed");
        for (term_idx, term) in sorted_terms.iter().enumerate() {
            builder
                .insert(term.as_bytes(), term_idx as u64)
                .expect("insert term");
        }
        builder.finish().expect("finish fst");

        let mmap_index = MmapIndex::open(test_index_path).expect("open index failed");
        let dictionary = TermDictionary::open(test_fst_path).expect("open dict failed");
        let pipeline = TokenizerPipeline::new();

        // Query: "alpha beta gamma" with top_k = 2
        let top2_res = search_combined_mmap(
            "alpha beta gamma",
            &mmap_index,
            &dictionary,
            &pipeline,
            1.0,
            DEFAULT_EPSILON,
            2,
        );
        assert_eq!(top2_res.len(), 2);
        assert_eq!(top2_res[0].0.hex_id, "doc0");
        assert_eq!(top2_res[1].0.hex_id, "doc1");
        assert!(top2_res[0].1 > top2_res[1].1);

        // Query with top_k = 6 -> all 6 docs returned in order
        let all_res = search_combined_mmap(
            "alpha beta gamma",
            &mmap_index,
            &dictionary,
            &pipeline,
            1.0,
            DEFAULT_EPSILON,
            6,
        );
        assert_eq!(all_res.len(), 6);
        assert_eq!(all_res[0].0.hex_id, "doc0");
        assert_eq!(all_res[1].0.hex_id, "doc1");

        // Top 2 scores match exactly between top_k=2 and top_k=6
        assert!((top2_res[0].1 - all_res[0].1).abs() < 1e-9);
        assert!((top2_res[1].1 - all_res[1].1).abs() < 1e-9);

        let _ = std::fs::remove_file(test_index_path);
        let _ = std::fs::remove_file(test_fst_path);
    }
}
